# Generated by Django 5.2.7 on 2025-10-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='oracion',
            name='categoria',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Familia', 'Familia'), ('Sanacion', 'Sanación'), ('Intercesion', 'Intercesión')], max_length=50),
        ),
    ]
