# Generated by Django 5.2.7 on 2025-10-04 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_ubicacion_alter_oracion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_multimedia',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video_youtube', 'Video de YouTube'), ('video_local', 'Video MP4')], default='imagen', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='video_local',
            field=models.FileField(blank=True, help_text='Sube un video en formato MP4', null=True, upload_to='eventos/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AddField(
            model_name='evento',
            name='video_youtube_url',
            field=models.URLField(blank=True, help_text='Ingresa la URL del video de YouTube', null=True),
        ),
    ]
