# Generated by Django 5.2.7 on 2025-10-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_tipo_multimedia_evento_video_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='tipo_multimedia',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='video_local',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='video_youtube_url',
        ),
        migrations.AddField(
            model_name='evento',
            name='formulario_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Formulario Google'),
        ),
    ]
