# Generated by Django 5.2.7 on 2025-10-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_evento_tipo_multimedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_multimedia',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('video_youtube', 'Video de YouTube'), ('video_local', 'Video Local')], default='ninguno', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='video_local',
            field=models.FileField(blank=True, null=True, upload_to='eventos/videos/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='video_youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
