# Generated by Django 5.2.7 on 2025-10-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evento_tipo_multimedia_evento_video_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='preferencia_visualizacion',
            field=models.CharField(choices=[('imagen', 'Mostrar Imagen'), ('video', 'Mostrar Video')], default='imagen', help_text='Seleccione qué mostrar en el carrusel cuando el evento tenga tanto imagen como video', max_length=20),
        ),
    ]
