# Generated by Django 5.2.7 on 2025-10-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_evento_preferencia_visualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='orden_carrusel',
            field=models.IntegerField(default=0, help_text='Orden en que aparecerá en el carrusel (menor número = primero)'),
        ),
    ]
