# Generated by Django 5.2.7 on 2025-10-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_evento_orden_carrusel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['orden_carrusel', '-fecha'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_fin_publicacion',
            field=models.DateTimeField(blank=True, help_text='Fecha hasta la que el evento será visible. Si está vacío, el evento será visible indefinidamente.', null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_inicio_publicacion',
            field=models.DateTimeField(blank=True, help_text='Fecha desde la que el evento será visible. Si está vacío, el evento será visible inmediatamente.', null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='orden_carrusel',
            field=models.IntegerField(default=0, help_text='Orden en el carrusel (1-5 para mostrar, 0 para no mostrar). Los eventos con 0 aparecerán en próximos eventos.'),
        ),
    ]
