# Generated by Django 5.2.7 on 2025-11-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_evento_options_evento_fecha_fin_publicacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_principal', models.ImageField(blank=True, help_text='Logo principal que aparece en el home y navegación', null=True, upload_to='configuracion/')),
                ('quienes_somos_titulo', models.CharField(default='Quiénes Somos', max_length=200, verbose_name='Título de Quiénes Somos')),
                ('quienes_somos_contenido', models.TextField(blank=True, help_text='Describe quién es HMSP y su misión', verbose_name='Contenido de Quiénes Somos')),
                ('quienes_somos_imagen', models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Imagen de Quiénes Somos')),
                ('historia_titulo', models.CharField(default='Nuestra Historia', max_length=200, verbose_name='Título de Historia')),
                ('historia_contenido', models.TextField(blank=True, help_text='Cuenta la historia de HMSP', verbose_name='Contenido de Historia')),
                ('historia_imagen', models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Imagen de Historia')),
                ('vocaciones_titulo', models.CharField(default='Vocaciones', max_length=200, verbose_name='Título de Vocaciones')),
                ('vocaciones_contenido', models.TextField(blank=True, help_text='Información sobre vocaciones y llamados', verbose_name='Contenido de Vocaciones')),
                ('vocaciones_imagen', models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Imagen de Vocaciones')),
                ('contacto_direccion', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('contacto_telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('contacto_horario', models.TextField(blank=True, help_text='Horarios de atención al público', verbose_name='Horario de Atención')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
