# Generated by Django 5.2.7 on 2025-11-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_configuracionsitio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='historia_imagen',
            field=models.ImageField(blank=True, help_text='Dimensiones recomendadas: 800x500 píxeles. Formato: JPG o PNG. Tamaño máximo: 1.5MB.', null=True, upload_to='configuracion/', verbose_name='Imagen de Historia'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='logo_principal',
            field=models.ImageField(blank=True, help_text='ESPECIFICACIONES DEL LOGO: Dimensiones recomendadas: 200x80 píxeles (máximo 300x120). Formato: PNG con fondo transparente (preferido) o JPG. Tamaño máximo: 500KB. El logo se mostrará con altura de 60px en la navegación.', null=True, upload_to='configuracion/'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='quienes_somos_imagen',
            field=models.ImageField(blank=True, help_text='Dimensiones recomendadas: 1200x600 píxeles. Formato: JPG o PNG. Tamaño máximo: 2MB.', null=True, upload_to='configuracion/', verbose_name='Imagen de Quiénes Somos'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='vocaciones_imagen',
            field=models.ImageField(blank=True, help_text='Dimensiones recomendadas: 800x500 píxeles. Formato: JPG o PNG. Tamaño máximo: 1.5MB.', null=True, upload_to='configuracion/', verbose_name='Imagen de Vocaciones'),
        ),
    ]
