# Generated by Django 5.2.7 on 2025-11-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_configuracionsitio_historia_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, help_text='ESPECIFICACIONES: Dimensiones: 1200x800 píxeles (relación 3:2) para carrusel principal, o 600x400 píxeles para vista de lista. Formato: JPG (preferido) o PNG. Tamaño máximo: 2MB. La imagen se optimizará automáticamente para web.', null=True, upload_to='eventos/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, help_text='ESPECIFICACIONES: Dimensiones: 800x600 píxeles (relación 4:3) para portada, o 400x300 píxeles para miniatura. Formato: JPG (preferido) o PNG. Tamaño máximo: 1.5MB. Usar imágenes de alta calidad y bien iluminadas.', null=True, upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='ESPECIFICACIONES: Dimensiones: 400x400 píxeles (cuadrada, 1:1). Formato: JPG (preferido) o PNG. Tamaño máximo: 500KB. Usar foto de rostro centrada con buena iluminación.', null=True, upload_to='testimonios/'),
        ),
    ]
