# Generated by Django 5.2.7 on 2025-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_evento_imagen_alter_noticia_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonio',
            options={'ordering': ['-destacado', '-creado'], 'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
        migrations.AddField(
            model_name='testimonio',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar para mostrar en la página principal. Solo los primeros 3 testimonios destacados se mostrarán.'),
        ),
    ]
