# Generated by Django 5.2.7 on 2025-11-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_testimonio_options_testimonio_destacado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonio',
            options={'ordering': ['orden_destacado', '-creado'], 'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
        migrations.AddField(
            model_name='testimonio',
            name='orden_destacado',
            field=models.IntegerField(default=0, help_text='Orden de visualización en la página principal (1, 2 o 3). Use 0 para no destacar.'),
        ),
    ]
