# Generated by Django 5.2.7 on 2025-11-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mensajecontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apostolado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion_corta', models.TextField(help_text='Breve descripción para el menú', max_length=300, verbose_name='Descripción Corta')),
                ('descripcion', models.TextField(verbose_name='Descripción Completa')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa del apostolado (Recomendado: 800x600px, máx 2MB)', null=True, upload_to='apostolados/', verbose_name='Imagen')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en el menú (menor número = primero)', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apostolado',
                'verbose_name_plural': 'Apostolados',
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
