# Generated by Django 5.2.7 on 2025-11-19 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_apostolado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostolado',
            name='imagen',
            field=models.FileField(blank=True, help_text='Imagen representativa del apostolado (Formatos: JPG, PNG, SVG. Recomendado: 800x600px, máx 2MB)', null=True, upload_to='apostolados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Imagen'),
        ),
    ]
