# Generated by Django 5.2.7 on 2025-11-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_apostolado_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='biblioteca_oraciones_contenido',
            field=models.TextField(blank=True, help_text='Descripción de la colección de oraciones disponibles', verbose_name='Contenido de Biblioteca de Oraciones'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='biblioteca_oraciones_imagen',
            field=models.ImageField(blank=True, help_text='Dimensiones recomendadas: 800x500 píxeles. Formato: JPG o PNG. Tamaño máximo: 1.5MB.', null=True, upload_to='configuracion/', verbose_name='Imagen de Biblioteca de Oraciones'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='biblioteca_oraciones_titulo',
            field=models.CharField(default='Biblioteca de Oraciones', max_length=200, verbose_name='Título de Biblioteca de Oraciones'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='boletin_mensual_contenido',
            field=models.TextField(blank=True, help_text='Descripción del boletín y cómo suscribirse', verbose_name='Contenido de Boletín Mensual'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='boletin_mensual_imagen',
            field=models.ImageField(blank=True, help_text='Dimensiones recomendadas: 800x500 píxeles. Formato: JPG o PNG. Tamaño máximo: 1.5MB.', null=True, upload_to='configuracion/', verbose_name='Imagen de Boletín Mensual'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='boletin_mensual_titulo',
            field=models.CharField(default='Boletín Mensual', max_length=200, verbose_name='Título de Boletín Mensual'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='donaciones_contenido',
            field=models.TextField(blank=True, help_text='Información sobre cómo realizar donaciones', verbose_name='Contenido de Donaciones'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='donaciones_imagen',
            field=models.ImageField(blank=True, help_text='Dimensiones recomendadas: 800x500 píxeles. Formato: JPG o PNG. Tamaño máximo: 1.5MB.', null=True, upload_to='configuracion/', verbose_name='Imagen de Donaciones'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='donaciones_titulo',
            field=models.CharField(default='Donaciones', max_length=200, verbose_name='Título de Donaciones'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='material_espiritual_contenido',
            field=models.TextField(blank=True, help_text='Información sobre material de formación espiritual', verbose_name='Contenido de Material Espiritual'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='material_espiritual_imagen',
            field=models.ImageField(blank=True, help_text='Dimensiones recomendadas: 800x500 píxeles. Formato: JPG o PNG. Tamaño máximo: 1.5MB.', null=True, upload_to='configuracion/', verbose_name='Imagen de Material Espiritual'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='material_espiritual_titulo',
            field=models.CharField(default='Material Espiritual', max_length=200, verbose_name='Título de Material Espiritual'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='recursos_contenido',
            field=models.TextField(blank=True, help_text='Información general sobre los recursos disponibles', verbose_name='Contenido de Recursos'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='recursos_imagen',
            field=models.ImageField(blank=True, help_text='Dimensiones recomendadas: 1200x600 píxeles. Formato: JPG o PNG. Tamaño máximo: 2MB.', null=True, upload_to='configuracion/', verbose_name='Imagen de Recursos'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='recursos_titulo',
            field=models.CharField(default='Recursos', max_length=200, verbose_name='Título de Recursos'),
        ),
    ]
