# Generated by Django 5.2.7 on 2025-11-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_configuracionsitio_biblioteca_oraciones_contenido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apostolado',
            name='imagen',
            field=models.ImageField(blank=True, help_text='ESPECIFICACIONES: Dimensiones: 800x600px (recomendado). Formato: JPG, PNG, SVG. Máx 2MB.', null=True, upload_to='apostolados/', verbose_name='Imagen'),
        ),
    ]
