# Generated by Django 5.2.7 on 2025-11-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_suscripcion_alter_apostolado_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='telefono',
            field=models.CharField(help_text='Número chileno, 9 dígitos, inicia con 9 o 2', max_length=9),
        ),
    ]
